#install.packages(c("raster", "ncdf4", "sf", "rgdal", "leaflet", "rasterVis", "purrr", 
                   #"gdalUtilities", "sp", "tiff", "dplyr", "zoo", "tidyr", "lubridate",
                   #"ggplot2", "gridExtra", "lattice", "lubridate", "tools", "terra", 
                   #"RColorBrewer", "gridExtra", "ggcorrplot", "factoextra", "readr", 
                   #"randomForest", "pdp", "latticeExtra", "fs", "caret", "keras", 
                   #"spgwr", "maptools", "readr", "spatialEco", "stars", "gstat", 
                   #"automap", "optional", "doParallel", "foreach", "cowplot", "png", 
                   #"tinytex", "meteo", "nabor", "ranger", "plyr", "CAST", "ggsn", "mlr", 
                   #"tuneRanger"))

#install.packages("meteo", repos="http://R-Forge.R-project.org")

# Load the libraries after installation
library(raster)
library(ncdf4)
library(sf)
library(rgdal)
library(leaflet)
library(rasterVis)
library(purrr)
library(gdalUtilities)
library(sp)
library(tiff)
library(dplyr)
library(zoo)
#library(tid)
        

library(raster)
library(ncdf4)
library(sf)
library(rgdal)
library(leaflet)
library(rasterVis)
library(purrr)
library(gdalUtilities)
library(sp)
library(tiff)
library(dplyr)
library(rasterVis)
library(zoo)
library(tidyr)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(lattice)
#library(magick)
library(lubridate)
library(tools)
library(terra)
library(RColorBrewer)  
library(gridExtra)
library(gridExtra)
library(ggcorrplot)
library(factoextra)
library(readr)
library(randomForest)
library(pdp)
library(latticeExtra)
library(fs)
library(caret)

library(keras)
library(spgwr)
library(ggplot2)
library(maptools)
library(readr)
#library(xlsx)
library(spatialEco)
library(sf)
library(stars)
library(gstat)
library(automap)
library(raster)
library(dplyr)
library(sp)
library(gstat)
library(raster)
library(rgdal)
library(leaflet)
library(ggpubr)
#install.packages("optional")  # Install only if you haven't installed it already
library(optional)
#install.packages("gstat")  # Install only if you haven't installed it already
library(gstat)
#update.packages(ask = FALSE)

library(doParallel)
library(foreach)
library(cowplot)

library(pdp)
library(png)
library(tinytex)

#install.packages("meteo", repos="http://R-Forge.R-project.org")
library(meteo) # rforge

library(sp)
#library(plotGoogleMaps)
library(ggplot2)
library(nabor)
library(ranger)
library(rgdal)
library(raster)
library(doParallel)
library(gstat)
library(plyr)
library(caret)
library(CAST)
library(ggpubr)
library(automap)
library(ggpubr)
library(grid)
library(hexbin)
library(ggsn)
library(mlr)
library(tuneRanger)


